#pragma once

#include "freertos/FreeRTOS.h"

#define APP_SENSOR_TASK_PRIORITY 8
#define APP_STORAGE_TASK_PRIORITY 5
#define APP_SUPERVISOR_TASK_PRIORITY 4
#define APP_COMM_TASK_PRIORITY 3

#define APP_SENSOR_TASK_STACK 6144
#define APP_STORAGE_TASK_STACK 6144
#define APP_SUPERVISOR_TASK_STACK 4096
#define APP_COMM_TASK_STACK 6144

#define APP_SENSOR_TASK_CORE 1
#define APP_SERVICE_TASK_CORE 0

#define APP_SAMPLE_QUEUE_LENGTH 12
#define APP_COMMAND_QUEUE_LENGTH 10
#define APP_STORAGE_QUEUE_TIMEOUT pdMS_TO_TICKS(20)
#define APP_HEALTH_PERIOD_MS 5000U
#define APP_COLLECTION_PERIOD_MS 20000U
#define APP_COLLECTION_WINDOW_MS 20000U

#define APP_EVENT_RECORDING BIT0
#define APP_EVENT_STOP_REQUESTED BIT1
#define APP_EVENT_STORAGE_READY BIT2
#define APP_EVENT_SENSOR_READY BIT3
#define APP_EVENT_FATAL_FAULT BIT4
